### ISSUE TITLE
GPS symbol layer name incorrect in the legend of a printout

### ISSUE THREAD

**Issue by DavidSpriggs** [Esri/arcgis-dijit-locate-button-js#2]
When printing a map that has a gps point on it, the legend has 'Override 1' as the layer name. This is due to the gps graphic being added directly to the maps graphics layer without a renderer. The printing service can only properly render a legend when a renderer is present. To fix, add a graphics layer with a renderer for the gps point. This will also help separate other issue when users try to use the map's graphics layer.

![image](https://f.cloud.github.com/assets/661156/2043138/96a0b4fc-89da-11e3-9a34-ffad13e5d2f2.png)

Se an example on how to fix this in my simple geolocation widget:
https://github.com/DavidSpriggs/ConfigurableViewerJSAPI/blob/master/viewer/js/gis/dijit/GeoLocation.js#L40

You can do a test print here to see the diffrence:
http://davidspriggs.github.io/ConfigurableViewerJSAPI/viewer/

![image](https://f.cloud.github.com/assets/661156/2043150/cafd456c-89da-11e3-8e10-c52ddf9977db.png)

**Comment by ritanshu-goel** [comment]
is it taking location from network or GPS? how can we access location using Mobile GPS?
